sudo: required

language: node_js
node_js:
  - '8.9.1'

services: 
  mongodb
  elasticsearch

branches:
  only:
    - master

before script:
 - sleep 15
 - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  - sudo rm /var/lib/mongodb/mongod.lock
  - sudo service mongod restart
  - npm test